name: Selenium Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Selenium tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        pytest tests/ -m "ui and smoke" --maxfail=5 --disable-warnings --html=reports/report.html

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html